workflows:
  my-workflow:
    name: build iOS
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "build success !!"
    artifacts:
      - build/**/outputs/bundle/**/*.aab
